### ISSUE TITLE
Stackoverflow survey 2023 just got published

### ISSUE THREAD

**Issue by sueszli** [codereport/plr#15]
link: https://survey.stackoverflow.co/2023/?utm_source=banner&utm_medium=display&utm_campaign=dev-survey-results-2023&utm_content=survey-results#overview

---

I would really apreciate an update as your ranking is the best one I have ever seen!
Thanks :)

Btw I'm a huge fan and hope to one day make a meaningful contribution to the community like you did.

**Comment by codereport** [comment]
Thanks for notifying me! The website has been update! If you want to contribute a PR in the future these are the changes required: https://github.com/codereport/plr/commit/f135eea1c036fdb264c9faf696d42a4193f64ace

**Comment by sueszli** [comment]
Fantastic! thank you so much.

I'm not familiar with clojure but the projects structure seems very intuitive and I now know better.

Again: I'm a huge fan and so happy that you responded to this issue.
