### ISSUE TITLE
Combining TIOBE and IEEE Spectrum breaks the top slot

### ISSUE THREAD

**Issue by sean-parent** [codereport/plr#16]
<img width="701" alt="image" src="https://github.com/codereport/plr/assets/2279724/382e8626-3fc3-4419-acfa-d001911d964b">

**Comment by codereport** [comment]
Thanks @sean-parent :pray: It was a blank line at EOF problem. I added a check to make sure it won't happen in the future : ) https://github.com/codereport/plr/commit/f10e1da7d58c85b39362df95d4dc6225f0749f17
