### ISSUE TITLE
Choose better font

### ISSUE THREAD

**Issue by codereport** [codereport/plr#9]
Initially I chose `Courier` as it is the only cross-platform monospace font. However, it looks "thin" on Windows and mobile. Figure out how to use `Consolas` or `JetBrains Mono`

**Comment by Lakelimbo** [comment]
would you mind using an external font? If not, Ubuntu Mono or IBX Plex Mono are good ones

**Comment by codereport** [comment]
@Lakelimbo What is an "external" font?

**Comment by Lakelimbo** [comment]
> @Lakelimbo What is an "external" font?

either:
- loading a custom font locally
- using `<link>` or `@import` from a place hosting the fonts (such as Google Fonts)
